// Snapshot of every card's fixed "rarity" field as it existed in data/*.json before rarity became
// a per-pull roll. Used ONLY by engine.js's getCollection() to lift pre-rarity-split collection
// saves into the new nested { rarity: { variant: count } } shape - never read for anything else.
export const LEGACY_CARD_RARITY = {
  "char-sadie": "rare",
  "char-zo": "common",
  "char-silvy": "common",
  "char-llewellyn": "rare",
  "char-cagney": "common",
  "char-bethany": "common",
  "char-blac": "rare",
  "char-let": "common",
  "char-saxony": "common",
  "char-starlot": "rare",
  "char-sevura": "common",
  "char-d": "common",
  "char-rufus": "rare",
  "char-celia": "common",
  "char-brb": "common",
  "mech-cidermayer": "common",
  "mech-linwood": "common",
  "mech-sydney": "common",
  "mech-bowler": "common",
  "mech-myriad": "common",
  "mech-gigatear": "common",
  "mech-olaf": "common",
  "mech-lasereater": "common",
  "mech-cidermajor": "common",
  "mech-leadfoot": "common",
  "mech-cassidy": "common",
  "mech-ciderheart": "common",
  "mech-ciderlord": "common",
  "mech-coldshoulder": "common",
  "mech-derrick": "common",
  "dm-dark-fragile-core": "legendary",
  "dm-dark-nil-fate": "legendary",
  "dm-dark-lonliness": "legendary",
  "dm-dark-possession": "legendary",
  "dm-shaded-fragile-core": "legendary",
  "dm-shaded-nil-fate": "legendary",
  "dm-shaded-lonliness": "legendary",
  "dm-shaded-possession": "legendary",
  "wc-true-grit": "uncommon",
  "wc-fearless-heart": "uncommon",
  "wc-second-wind": "uncommon",
  "wc-overclock": "uncommon",
  "wc-shield-wall": "uncommon",
  "wc-ambush": "uncommon",
  "wc-sabotage": "uncommon",
  "wc-last-stand": "uncommon",
  "wc-second-chance": "uncommon",
  "arena-asteroid-clusters": "rare",
  "arena-darkest-nebula": "rare",
  "arena-satellite-field": "rare",
  "arena-ionic-storms": "rare",
  "arena-monster-graveyard": "rare",
  "arena-normal-space": "rare",
};
